name: 'Gem auto-tag'
description: 'Creates a tag with version from your .gemspec file'
branding:
  icon: tag
  color: purple
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  tag_prefix:
    description: 'Tag prefix'
    required: false
  working_directory:
    description: 'Gem directory'
    required: false
outputs:
  tag:
    description: 'Created tag'
  url:
    description: 'Ref URL'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.tag_prefix }}
    - ${{ inputs.working_directory }}
